spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_app_db
    username: postgres
    password: javawhizz
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true